### PR TITLE
Add TwoFA functionality to Nexus

### PR DESCRIPTION
**Pull request by jianba**
###  TwoFA development
-  [Recod](https://jianba.github.io/2019/10/13/2FA%E5%BC%80%E5%8F%91/)

### CODE REVIEW

**Comment by jianba** [comment]
[Record & Questions](https://jianba.github.io/2019/10/13/2FA%E5%BC%80%E5%8F%91/)

**Comment by Anduin2017** [comment]
Still blocked by conflict.

**Comment by Anduin2017** [comment]
Why close this?

**Comment by Anduin2017** [comment]
We will keep working on this until all code issues have been solved. While I was trying to integrate the OAuth system by other providers.

**Comment by jianba** [comment]
> Why close this?

I read the book of agile software development roughly. I intend to mention a PR again. The reason why I do this is that there are many unexplained commits in this pr. if these commits are merged into the main branch, I think it will pollute the code of nexus. Still, my consideration is superfluous.

**Comment by Anduin2017** [comment]
Code is the value of us, not the function. We are working on an artwork, not a project.

**Comment by jianba** [comment]
> Code is the value of us, not the function. We are working on an artwork, not a project.

Got it

**Pull request closed without merging**
